-- alter_tests_fisicos.sql
-- Este script modifica la tabla "tests_fisicos" para permitir almacenar
-- múltiples pruebas individuales por cada estudiante.

-- 1. Eliminar la clave primaria y la restricción de clave foránea existentes.
-- La restricción de clave foránea se elimina porque depende de la clave primaria.
ALTER TABLE "public"."tests_fisicos" DROP CONSTRAINT "tests_fisicos_pkey";

-- 2. Añadir una nueva columna 'id' que será la nueva clave primaria para cada registro de prueba.
ALTER TABLE "public"."tests_fisicos" ADD COLUMN "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 3. Crear un tipo ENUM para las categorías de las pruebas.
-- Esto asegura que solo se puedan insertar valores válidos ('Velocidad', 'Fuerza', 'Resistencia').
-- Si el tipo ya existe, esta línea dará un error, lo cual es seguro ignorar si ya lo creaste.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'categoria_prueba_enum') THEN
        CREATE TYPE public.categoria_prueba_enum AS ENUM ('Velocidad', 'Fuerza', 'Resistencia');
    END IF;
END$$;

-- 4. Añadir las nuevas columnas a la tabla tests_fisicos.
ALTER TABLE "public"."tests_fisicos"
ADD COLUMN "categoria" public.categoria_prueba_enum NOT NULL,
ADD COLUMN "prueba" TEXT NOT NULL,
ADD COLUMN "unidad" TEXT, -- Opcional, por ej: 'segundos', 'metros', 'repeticiones'
ADD COLUMN "resultado" TEXT NOT NULL,
ADD COLUMN "created_at" TIMESTAMPTZ DEFAULT now() NOT NULL;

-- 5. Eliminar las columnas antiguas que ya no se usarán.
ALTER TABLE "public"."tests_fisicos"
DROP COLUMN "velocidad_fuerza",
DROP COLUMN "resistencia";

-- 6. Crear un índice en estudiante_id para acelerar las búsquedas.
CREATE INDEX IF NOT EXISTS idx_tests_fisicos_estudiante_id ON "public"."tests_fisicos"("estudiante_id");

\echo 'Tabla tests_fisicos modificada exitosamente.'