-- Suprime las advertencias de objetos no existentes para que el script se pueda ejecutar varias veces
SET client_min_messages TO WARNING;

-- Elimina la política de seguridad a nivel de fila (RLS) de la tabla antigua si existe
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.tests_fisicos;

-- Elimina la tabla antigua si existe
DROP TABLE IF EXISTS public.tests_fisicos;

-- Crea un tipo ENUM para las categorías de las pruebas, lo que garantiza la consistencia de los datos
CREATE TYPE public.categoria_prueba_enum AS ENUM ('Velocidad', 'Fuerza', 'Resistencia');

-- Crea la nueva tabla para las pruebas físicas con la estructura solicitada
-- Esta tabla permite registrar múltiples pruebas para cada estudiante a lo largo del tiempo
CREATE TABLE public.tests_fisicos (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "estudiante_id" UUID NOT NULL,
    "categoria" public.categoria_prueba_enum NOT NULL,
    "prueba" TEXT NOT NULL,
    "unidad" TEXT,
    "resultado" NUMERIC NOT NULL,
    "fecha_prueba" DATE DEFAULT now() NOT NULL, -- Se añade una fecha para registrar cuándo se realizó la prueba

    CONSTRAINT "tests_fisicos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tests_fisicos_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES public.estudiantes("id") ON DELETE CASCADE
);

-- Vuelve a habilitar la seguridad a nivel de fila (RLS) en la nueva tabla
ALTER TABLE public.tests_fisicos ENABLE ROW LEVEL SECURITY;

-- Crea una política de RLS que permite a los usuarios autenticados realizar todas las operaciones (CRUD)
-- Esto asume que la autorización se gestiona a nivel de la aplicación
CREATE POLICY "Enable all for authenticated users" ON "public"."tests_fisicos"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Crea un índice en estudiante_id para mejorar el rendimiento de las consultas que filtran por estudiante
CREATE INDEX idx_tests_fisicos_estudiante_id ON public.tests_fisicos(estudiante_id);
