-- ####################################################################
-- # 1. DISEÑO DE LA BASE DE DATOS
-- ####################################################################

-- # RECOMENDACIÓN DE MODELADO DE DEPORTES:
-- # Se opta por una tabla intermedia (estudiante_deportes) para una relación muchos a muchos.
-- # Esta es la opción más flexible y recomendada, ya que permite que un estudiante
-- # practique más de un deporte en el futuro sin necesidad de cambiar el esquema de la BD.

-- Extensión para funciones de utilidad (si no está activada)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Primero, creamos los tipos enumerados (ENUMS) para datos controlados.
CREATE TYPE "public"."resultado_competencia" AS ENUM ('ORO', 'PLATA', 'BRONCE', 'OTRO');
CREATE TYPE "public"."tipo_sangre_enum" AS ENUM ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');

-- Tabla para almacenar los deportes permitidos.
CREATE TABLE "public"."deportes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "deportes_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "deportes_nombre_key" UNIQUE ("nombre")
);

-- Tabla principal de estudiantes.
CREATE TABLE "public"."estudiantes" (
    "id" UUID DEFAULT uuid_generate_v4() NOT NULL,
    "cedula" VARCHAR(10) NOT NULL,
    "nombres_apellidos" TEXT NOT NULL,
    "direccion" TEXT,
    "correo" TEXT,
    "carrera" TEXT,
    "facultad" TEXT,
    "fecha_nacimiento" DATE NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT "estudiantes_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "estudiantes_cedula_key" UNIQUE ("cedula"),
    CONSTRAINT "estudiantes_correo_check" CHECK (correo ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);

-- Tabla para la relación muchos a muchos entre estudiantes y deportes.
CREATE TABLE "public"."estudiante_deportes" (
    "estudiante_id" UUID NOT NULL,
    "deporte_id" BIGINT NOT NULL,
    CONSTRAINT "estudiante_deportes_pkey" PRIMARY KEY ("estudiante_id", "deporte_id"),
    CONSTRAINT "estudiante_deportes_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES "public"."estudiantes"("id") ON DELETE CASCADE,
    CONSTRAINT "estudiante_deportes_deporte_id_fkey" FOREIGN KEY ("deporte_id") REFERENCES "public"."deportes"("id") ON DELETE CASCADE
);

-- Tabla para la ficha médica (relación 1 a 1 con estudiantes).
CREATE TABLE "public"."fichas_medicas" (
    "estudiante_id" UUID NOT NULL,
    "tipo_sangre" "public"."tipo_sangre_enum",
    "patologias" TEXT,
    "ultima_consulta_medica" DATE,
    CONSTRAINT "fichas_medicas_pkey" PRIMARY KEY ("estudiante_id"),
    CONSTRAINT "fichas_medicas_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES "public"."estudiantes"("id") ON DELETE CASCADE
);

CREATE TYPE "public"."categoria_prueba_enum" AS ENUM ('velocidad', 'fuerza', 'resistencia');

-- Tabla para los tests físicos (relación 1 a muchos con estudiantes)
CREATE TABLE "public"."tests_fisicos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "estudiante_id" UUID NOT NULL,
    "categoria" "public"."categoria_prueba_enum" NOT NULL,
    "prueba" TEXT NOT NULL,
    "unidad" TEXT,
    "resultado" NUMERIC NOT NULL,
    "fecha_prueba" DATE DEFAULT now() NOT NULL,
    CONSTRAINT "tests_fisicos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tests_fisicos_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES "public"."estudiantes"("id") ON DELETE CASCADE
);
CREATE INDEX idx_tests_fisicos_estudiante_id ON public.tests_fisicos(estudiante_id);

-- Tabla para el record deportivo (relación 1 a muchos con estudiantes).
CREATE TABLE "public"."records_deportivos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "estudiante_id" UUID NOT NULL,
    "nombre_competencia" TEXT NOT NULL,
    "fecha_competencia" DATE NOT NULL,
    "resultado" "public"."resultado_competencia",
    "puesto" INT,
    CONSTRAINT "records_deportivos_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "records_deportivos_estudiante_id_fkey" FOREIGN KEY ("estudiante_id") REFERENCES "public"."estudiantes"("id") ON DELETE CASCADE
);

-- Insertar los deportes iniciales
INSERT INTO "public"."deportes" (nombre) VALUES
('Taekwondo'),
('Judo'),
('Wushu'),
('Karate Do');


-- ####################################################################
-- # 2. VISTA PARA CALCULAR LA EDAD
-- ####################################################################
-- Esta vista simplifica las consultas al proveer la edad calculada.
CREATE OR REPLACE VIEW "public"."v_estudiantes_con_edad" AS
SELECT
    e.*,
    date_part('year', age(e.fecha_nacimiento)) AS edad
FROM
    "public"."estudiantes" e;


-- ####################################################################
-- # 3. FUNCIÓN RPC PARA OBTENER FICHA COMPLETA
-- ####################################################################
-- Esta función simplifica enormemente el código del frontend.
-- Recibe una cédula y devuelve un único objeto JSON con toda la información.

CREATE OR REPLACE FUNCTION get_student_full_details(p_cedula VARCHAR(10))
RETURNS JSONB AS $$
DECLARE
    result JSONB;
BEGIN
    SELECT
        jsonb_build_object(
            'id', e.id,
            'cedula', e.cedula,
            'nombres_apellidos', e.nombres_apellidos,
            'direccion', e.direccion,
            'correo', e.correo,
            'carrera', e.carrera,
            'facultad', e.facultad,
            'fecha_nacimiento', e.fecha_nacimiento,
            'edad', date_part('year', age(e.fecha_nacimiento)),
            'ficha_medica', fm,
            'test_fisicos', tf,
            'deportes', COALESCE(
                (SELECT jsonb_agg(d.nombre)
                 FROM public.estudiante_deportes ed
                 JOIN public.deportes d ON ed.deporte_id = d.id
                 WHERE ed.estudiante_id = e.id),
                '[]'::jsonb
            ),
            'records_deportivos', COALESCE(
                (SELECT jsonb_agg(rd.*)
                 FROM public.records_deportivos rd
                 WHERE rd.estudiante_id = e.id),
                '[]'::jsonb
            )
        )
    INTO result
    FROM
        public.estudiantes e
    LEFT JOIN
        public.fichas_medicas fm ON e.id = fm.estudiante_id
    LEFT JOIN
        public.tests_fisicos tf ON e.id = tf.estudiante_id
    WHERE
        e.cedula = p_cedula;

    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- ####################################################################
-- # 4. FUNCIÓN RPC PARA CREAR FICHA COMPLETA DE ESTUDIANTE
-- ####################################################################
-- Esta función inserta un estudiante y todos sus datos asociados
-- en una sola transacción.

CREATE OR REPLACE FUNCTION create_full_student(
    p_cedula VARCHAR(10),
    p_nombres_apellidos TEXT,
    p_fecha_nacimiento DATE,
    p_direccion TEXT,
    p_correo TEXT,
    p_carrera TEXT,
    p_facultad TEXT,
    p_deportes_nombres TEXT[], -- Array de nombres de deportes
    p_ficha_medica JSONB,
    p_test_fisicos JSONB,
    p_records_deportivos JSONB -- Array de objetos record deportivo
)
RETURNS UUID AS $$
DECLARE
    new_estudiante_id UUID;
    deporte_nombre TEXT;
    deporte_id_val BIGINT;
    record_deportivo JSONB;
BEGIN
    -- 1. Insertar datos del estudiante
    INSERT INTO public.estudiantes (
        cedula, nombres_apellidos, fecha_nacimiento, direccion, correo, carrera, facultad
    ) VALUES (
        p_cedula, p_nombres_apellidos, p_fecha_nacimiento, p_direccion, p_correo, p_carrera, p_facultad
    )
    RETURNING id INTO new_estudiante_id;

    -- 2. Insertar ficha médica
    INSERT INTO public.fichas_medicas (
        estudiante_id, tipo_sangre, patologias, ultima_consulta_medica
    ) VALUES (
        new_estudiante_id,
        (p_ficha_medica->>'tipo_sangre')::"public"."tipo_sangre_enum",
        p_ficha_medica->>'patologias',
        CASE WHEN p_ficha_medica->>'ultima_consulta_medica' = '' THEN NULL ELSE (p_ficha_medica->>'ultima_consulta_medica')::DATE END
    );

    -- 3. Insertar tests físicos
    INSERT INTO public.tests_fisicos (
        estudiante_id, velocidad_fuerza, resistencia
    ) VALUES (
        new_estudiante_id,
        CASE WHEN p_test_fisicos->>'velocidad_fuerza' = '' THEN NULL ELSE (p_test_fisicos->>'velocidad_fuerza')::NUMERIC END,
        CASE WHEN p_test_fisicos->>'resistencia' = '' THEN NULL ELSE (p_test_fisicos->>'resistencia')::NUMERIC END
    );

    -- 4. Insertar deportes asociados
    FOREACH deporte_nombre IN ARRAY p_deportes_nombres LOOP
        SELECT id INTO deporte_id_val FROM public.deportes WHERE nombre = deporte_nombre;
        IF deporte_id_val IS NOT NULL THEN
            INSERT INTO public.estudiante_deportes (estudiante_id, deporte_id)
            VALUES (new_estudiante_id, deporte_id_val);
        END IF;
    END LOOP;

    -- 5. Insertar récords deportivos
    IF jsonb_array_length(p_records_deportivos) > 0 THEN
        FOR record_deportivo IN SELECT * FROM jsonb_array_elements(p_records_deportivos) LOOP
            INSERT INTO public.records_deportivos (
                estudiante_id, nombre_competencia, fecha_competencia, resultado, puesto
            ) VALUES (
                new_estudiante_id,
                record_deportivo->>'nombre_competencia',
                (record_deportivo->>'fecha_competencia')::DATE,
                (record_deportivo->>'resultado')::"public"."resultado_competencia",
                CASE WHEN record_deportivo->>'puesto' = '' THEN NULL ELSE (record_deportivo->>'puesto')::INT END
            );
        END LOOP;
    END IF;

    RETURN new_estudiante_id;

END;
$$ LANGUAGE plpgsql;


-- ####################################################################
-- # 5. POLÍTICAS DE SEGURIDAD (ROW LEVEL SECURITY - RLS)
-- ####################################################################

-- Habilitamos RLS en todas las tablas.
ALTER TABLE "public"."estudiantes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."deportes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."estudiante_deportes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."fichas_medicas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tests_fisicos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."records_deportivos" ENABLE ROW LEVEL SECURITY;

-- Dado que es una app de un solo administrador, la política más simple
-- es permitir el acceso completo a cualquier usuario autenticado.
-- La seguridad se basa en que solo el admin tendrá credenciales.

-- Políticas para 'estudiantes'
CREATE POLICY "Enable all for authenticated users" ON "public"."estudiantes"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Políticas para 'deportes'
CREATE POLICY "Enable read for all users" ON "public"."deportes"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for authenticated users" ON "public"."deportes"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

-- Políticas para 'estudiante_deportes'
CREATE POLICY "Enable all for authenticated users" ON "public"."estudiante_deportes"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Políticas para 'fichas_medicas'
CREATE POLICY "Enable all for authenticated users" ON "public"."fichas_medicas"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Políticas para 'tests_fisicos'
CREATE POLICY "Enable all for authenticated users" ON "public"."tests_fisicos"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Políticas para 'records_deportivos'
CREATE POLICY "Enable all for authenticated users" ON "public"."records_deportivos"
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);
