-- ####################################################################
-- # ACTUALIZACIONES DE ESQUEMA: TABLAS FACULTADES Y CARRERAS
-- ####################################################################

-- 1. Crear la tabla de facultades
CREATE TABLE "public"."facultades" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "facultades_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "facultades_nombre_key" UNIQUE ("nombre")
);

-- Habilitar RLS para la nueva tabla
ALTER TABLE "public"."facultades" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."facultades"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- 2. Crear la tabla de carreras, relacionada con facultades
CREATE TABLE "public"."carreras" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" TEXT NOT NULL,
    "facultad_id" BIGINT NOT NULL,
    CONSTRAINT "carreras_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "carreras_nombre_key" UNIQUE ("nombre"),
    CONSTRAINT "carreras_facultad_id_fkey" FOREIGN KEY ("facultad_id") REFERENCES "public"."facultades"("id") ON DELETE CASCADE
);

-- Habilitar RLS para la nueva tabla
ALTER TABLE "public"."carreras" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all users" ON "public"."carreras"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- 3. Insertar datos de ejemplo (puedes modificar esto según tus necesidades)
INSERT INTO "public"."facultades" (nombre) VALUES
('Facultad de Ingeniería Eléctrica y Electrónica (FIEE)'),
('Facultad de Ingeniería de Sistemas (FIS)'),
('Facultad de Ingeniería Civil (FIC)');

INSERT INTO "public"."carreras" (nombre, facultad_id) VALUES
('Ingeniería en Electrónica y Telecomunicaciones', 1),
('Ingeniería en Electricidad', 1),
('Ingeniería de Software', 2),
('Ingeniería en Tecnologías de la Información', 2),
('Ingeniería Civil', 3);

-- 4. Modificar la tabla de estudiantes para usar la nueva relación
-- NOTA: Esto eliminará las columnas antiguas. Asegúrate de haber migrado los datos si es necesario.
ALTER TABLE "public"."estudiantes"
  DROP COLUMN IF EXISTS "carrera",
  DROP COLUMN IF EXISTS "facultad",
  ADD COLUMN "carrera_id" BIGINT,
  ADD CONSTRAINT "estudiantes_carrera_id_fkey" FOREIGN KEY ("carrera_id") REFERENCES "public"."carreras"("id") ON DELETE SET NULL;

-- ####################################################################
-- # FUNCIONES RPC PARA LISTAR FACULTADES Y CARRERAS
-- ####################################################################

-- Función para obtener todas las facultades
CREATE OR REPLACE FUNCTION get_facultades()
RETURNS TABLE(id BIGINT, nombre TEXT) AS $$
BEGIN
    RETURN QUERY SELECT f.id, f.nombre FROM public.facultades f ORDER BY f.nombre;
END;
$$ LANGUAGE plpgsql;

-- Función para obtener todas las carreras con su facultad
CREATE OR REPLACE FUNCTION get_carreras_con_facultad()
RETURNS TABLE(id BIGINT, nombre TEXT, facultad_id BIGINT, facultad_nombre TEXT) AS $$
BEGIN
    RETURN QUERY SELECT c.id, c.nombre, f.id, f.nombre FROM public.carreras c
    JOIN public.facultades f ON c.facultad_id = f.id
    ORDER BY f.nombre, c.nombre;
END;
$$ LANGUAGE plpgsql;